# Generated by Django 5.2.4 on 2025-09-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='emb',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
